#requires -Version 5.1
<#
.SYNOPSIS
    Builds the single-file scripts in dist/ from src/.
.DESCRIPTION
    dist/win-toolbox.ps1   - all tools + menu (irm menu.geyer.zone | iex)
    dist/adwcleaner.ps1    - AdwCleaner only
    dist/windows-update.ps1 - Windows Update only
    dist/software-setup.ps1 - Software Setup (profiles + catalog) only
    dist/inventory.ps1     - Inventory only
    dist/clean-traces.ps1  - Clean Traces only
    dist/winget.ps1        - install/repair WinGet only
    dist/harden.ps1        - Harden System Security only
    Every dist file is self-contained: common.ps1 + the needed tool(s) + a small entry block,
    wrapped in `& { }` so that running it via `irm | iex` leaves no variables, functions or
    preference changes behind in the caller's session.
.PARAMETER BaseUrl
    Where the dist files are published. Baked in as $SelfUrl so a non-admin irm|iex run can
    re-launch itself elevated.
#>
[CmdletBinding()]
param(
    [string]$BaseUrl = 'https://raw.githubusercontent.com/Bladeage/win-toolbox/main/dist',
    [string]$OutDir = (Join-Path $PSScriptRoot 'dist')
)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$version = (Get-Content (Join-Path $root 'VERSION') -Raw).Trim()

$targets = @(
    @{ Out = 'win-toolbox.ps1';    Parts = 'common', 'winget', 'tools/adwcleaner', 'tools/windows-update', 'tools/software', 'tools/inventory', 'tools/traces', 'tools/external', 'menu'
       Elevate = $true;  Param = 'param([string]$Tool)'; Entry = 'Show-Menu -Tool $Tool'; Description = 'All-in-one menu' },
    @{ Out = 'adwcleaner.ps1';     Parts = 'common', 'tools/adwcleaner'
       Elevate = $false; Param = ''; Entry = 'Invoke-AdwCleaner'; Description = 'Download, run and remove Malwarebytes AdwCleaner' },
    @{ Out = 'windows-update.ps1'; Parts = 'common', 'tools/windows-update'
       Elevate = $true;  Param = ''; Entry = 'Invoke-WindowsUpdate'; Description = 'Install all pending Windows updates (PSWindowsUpdate)' },
    @{ Out = 'software-setup.ps1'; Parts = 'common', 'winget', 'tools/software'
       Elevate = $true;  Param = ''; Entry = 'Invoke-SoftwareSetup'; Description = 'Software Setup - profiles and catalog via winget' },
    @{ Out = 'inventory.ps1';      Parts = 'common', 'tools/inventory'
       Elevate = $false; Param = ''; Entry = 'Invoke-Inventory'; Description = 'Hardware / OS / software inventory to CSV' },
    @{ Out = 'clean-traces.ps1';   Parts = 'common', 'tools/traces'
       Elevate = $false; Param = ''; Entry = 'Invoke-CleanTraces'; Description = 'Remove technician working traces (dry run by default)' },
    @{ Out = 'winget.ps1';         Parts = 'common', 'winget'
       Elevate = $false; Param = ''; Entry = 'Install-WinGet -Force'; Description = 'Install or repair WinGet (asheroto winget-install)' },
    @{ Out = 'harden.ps1';         Parts = 'common', 'winget', 'tools/external'
       Elevate = $true;  Param = ''; Entry = 'Install-HardenSystemSecurity'; Description = 'Install HotCakeX Harden System Security (MS Store)' }
)

function Read-Part([string]$Name) {
    $path = Join-Path $root "src/$Name.ps1"
    # normalise to LF while assembling; final file is written with CRLF for Windows
    return ((Get-Content $path -Raw) -replace "`r`n", "`n").TrimEnd()
}

$catalogJson = ((Get-Content (Join-Path $root 'catalog/software.json') -Raw) -replace "`r`n", "`n").TrimEnd()
if ($catalogJson -match "(?m)^'@") { throw "catalog/software.json contains a line starting with '@ - cannot embed as here-string" }

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
foreach ($t in $targets) {
    $selfUrl = "$BaseUrl/$($t.Out)"
    $body = ($t.Parts | ForEach-Object { Read-Part $_ }) -join "`n`n"
    if ($t.Parts -contains 'tools/software') {
        # embed the catalog so the dist file stays self-contained
        $body = "# ---- embedded catalog (catalog/software.json, generated by build-catalog.ps1) ----`n`$CatalogJson = @'`n$catalogJson`n'@`n`n" + $body
    }

    $elevateBlock = ''
    if ($t.Elevate) {
        $argLine = if ($t.Param) { '$elevArgs = if ($Tool) { "-Tool $Tool" } else { "" }' } else { '$elevArgs = ""' }
        $elevateBlock = @"
$argLine
if (Invoke-Elevated -SelfUrl `$SelfUrl -Arguments `$elevArgs) { return }
"@
    }

    $content = @"
<#
    win-toolbox - $($t.Description)
    Version $version | Generated by build.ps1 - do not edit, edit src/ instead.
    Source: https://github.com/Bladeage/win-toolbox
    Run:    irm $selfUrl | iex
#>
$($t.Param)
& {
`$SelfUrl = '$selfUrl'
`$ToolboxVersion = '$version'

$body

# ---- entry ----------------------------------------------------------------
$elevateBlock
try {
    $($t.Entry)
} catch {
    Write-Fail "Error: `$_"
}
$(if ($t.Entry -notlike 'Show-Menu*') { 'Wait-AnyKey' })
}
"@
    $outPath = Join-Path $OutDir $t.Out
    $crlf = ($content -replace "`r?`n", "`r`n")
    # ASCII-only, no BOM: identical bytes for irm|iex and for running the file in PS 5.1 / 7
    if ($crlf -match '[^\x00-\x7F]') { throw "$($t.Out): non-ASCII characters found - keep src/ ASCII-only" }
    [IO.File]::WriteAllText($outPath, $crlf, (New-Object Text.UTF8Encoding $false))
    Write-Host ("built {0,-22} {1,6:N0} bytes" -f $t.Out, (Get-Item $outPath).Length)
}
